### YamlMime:ModuleUnit
uid: learn-bizapps.powerapps-manage.3-powerapps-environments
title: Verstehen von Umgebungen in PowerApps
metadata:
  title: Verstehen von Umgebungen in PowerApps
  description: Erfahren Sie, wie Sie mit Umgebungen in PowerApps arbeiten.
  ms.date: 09/24/2018
  author: margoc
  ms.author: margoc
  ms.topic: interactive-tutorial
  ms.prod: learning-powerapps
  ms.openlocfilehash: c3f1796ee1ee65dc9088dfc655ca5ca8e6c175a1
  ms.sourcegitcommit: 255768424a95e14dc5767f1710feb755467861ee
  ms.translationtype: HT
  ms.contentlocale: de-DE
  ms.lasthandoff: 09/18/2018
  ms.locfileid: "46120113"
durationInMinutes: 12
content: '[!include[](includes/3-powerapps-environments.md)]'
