### YamlMime:ModuleUnit
uid: learn-bizapps.powerapps-manage.3-powerapps-environments
title: <span data-ttu-id="54018-101">Verstehen von Umgebungen in PowerApps</span><span class="sxs-lookup"><span data-stu-id="54018-101">Understand environments in PowerApps</span></span>
metadata:
  title: <span data-ttu-id="54018-102">Verstehen von Umgebungen in PowerApps</span><span class="sxs-lookup"><span data-stu-id="54018-102">Understand environments in PowerApps</span></span>
  description: <span data-ttu-id="54018-103">Erfahren Sie, wie Sie mit Umgebungen in PowerApps arbeiten.</span><span class="sxs-lookup"><span data-stu-id="54018-103">Learn how to work with environments in PowerApps.</span></span>
  ms.date: 09/24/2018
  author: margoc
  ms.author: margoc
  ms.topic: interactive-tutorial
  ms.prod: learning-powerapps
  ms.openlocfilehash: c3f1796ee1ee65dc9088dfc655ca5ca8e6c175a1
  ms.sourcegitcommit: 255768424a95e14dc5767f1710feb755467861ee
  ms.translationtype: HT
  ms.contentlocale: de-DE
  ms.lasthandoff: 09/18/2018
  ms.locfileid: "46120113"
durationInMinutes: 12
content: '[!include[](includes/3-powerapps-environments.md)]'
